### PR TITLE
fix signing requests with body content

### PR DESCRIPTION
**Pull request by deoxxa**
Previously this library would consume the request body without sending it to the destination. This is now corrected by reading, buffering, and re-forwarding the content.

### CODE REVIEW

**Comment by mhrabovcin** [comment]
I had issues doing `POST` requests against AWS Elastic Search service and I was getting `403` responses. I've tested this patch and it resolved ES issue.

**Comment by FrankStienhans2** [comment]
Thanks mhrabovcin. Your fix solved my issue.

**Comment by menkveldj** [comment]
Any chance of getting this fix committed into master soon? I'm working on a mobile app for a customer and would love to set my vendor.json to master.

Thanks.

**Comment by sha1sum** [comment]
Very sorry that this was list in my inbox.

**Comment by sha1sum** [comment]
@deoxxa I've added you into an acknowledgments section in the readme. Thank you for your patience and contribution.

**Pull request merged**
